### ISSUE TITLE
Não estou conseguindo com o npm

### ISSUE THREAD

**Issue by DaniloCruz** [ezefranca/campeonato-brasileiro-api#2]
o npm esta informando erros.

**Comment by ezefranca** [comment]
Tenta instalar as dependencias separadas:

npm install  es6-promise
npm install request
npm install  cheerio

**Comment by ezefranca** [comment]
@DaniloCruz arrumado, pode testar aqui:

https://npm.runkit.com/campeonato-brasileiro-api
